driverClassName=com.mysql.jdbc.Driver
url=jdbc:mysql://localhost:3306/student?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
#url=jdbc:mysql://127.0.0.1:3306/student?useUnicode=true&characterEncoding=utf8
username=root
password=root
characterEncoding=utf-8
initialSize=5
maxActive=100
maxWait=3000
validationQuery=SELECT 1
testWhileIdle=true
